llvm/builtins: Restrict packed attribute on Philox structure to LLVM>=20 (#3420)
It was not needed with older llvmlite/llvm versions and it causes issues
with older Numpy/ctypes leading to alignment issues like:

AssertionError: Size mismatch (_eval_state), numpy: 1140 vs. ctypes:1168

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>