Changes to: - State._parse_state_spec (duplicate preferences) - Function._get_modulated_param (use .parameters) Example Error in test_contrastive_hebbian_mechanism.TestContrastiveHebbian:   AttributeError: Parameter 'increment' has no attribute 'source'   ../psyneulink/core/globals/parameters.py:702: AttributeError