Refactor/functions/mod params (#1317)
* • ControlSignal
  - moving cost functions to new Cost Function

• ObjectiveFunctions
  - adding new Cost Function

* -

* -

* -

* -

* -

* -

* -

* -

* -

* -

* • TransferFunctions
  added TransferWithCosts

• ControlSignal
  modified to use TransferWithCosts

CURRENTLY COMPILES, BUT UNTESTED

* -

* -

* -

* -

* -

* -

* -

* • Component:
  _instantiate_attributes_before_function: allow it to parse and modify function arg

• ModulatoryMechanism:
  - _instantiate_modulatory_signal: added error filtering for ProjectionError and StateError

* -

* -

* -

* -

* • TransferWithCosts
  - passes all tests except tests/composition/test_control/TestModelBasedOptimizationControlMechanisms.test_nested_evc
    and LLVM

* -

* -

* -

* -

* • Function
  _get_modulated_param:  converted to using aliases of .parameters

* • Function
  _get_modulated_param:  converted to using aliases of .parameters

* CHANGE IN EARLIER COMMIT:
• State
  _parse_state_spec:  give precedence for any duplicate keys to state_specific_args vs. state_spec

* Changes to:
- State._parse_state_spec (duplicate preferences)
- Function._get_modulated_param (use .parameters)
Example Error in test_contrastive_hebbian_mechanism.TestContrastiveHebbian:
  AttributeError: Parameter 'increment' has no attribute 'source'
  ../psyneulink/core/globals/parameters.py:702: AttributeError

* -

* • Function
  - ModulatedParam: got rid of function_param_name
  - _get_modulated_param:  only returns ModulatedParam and funtion_param_val

* llvm/pytorch: Codestyle

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

* -

* -

* -

* -

* TransferWithCosts: fix validation method typo (will fail to run)

* TransferWithCosts: add dependent_components, pass execution_ids

* -

* -

* • Project
  - remove all traces of ModulationParam;
    replace uses with string that references modulated parameter

* -

* • Project
  ADDITIVE, ADDITIVE_PARAM, DISABLE, DISABLE_PARAM,
  MULTIPLICATIVE, MULTIPLICATIVE_PARAM, OVERRIDE AND OVERRIDE_PARAM
  moved to keywords

* • Function, State
  - moved _get_modulated_param from Function to State
  - added _get_aggregated_mod_val
    NOTE:  Currently only specifically recognizes MULTIPLICATIVE and ADDITIVE specs;
           uses MULTIPLICATIVE.  Needs to be use something like a
           modulation_aggregation_fct attribute once that is added to Parameters class

* PASSES ALL TESTS in tests/composition/test_control EXCEPT LLVM
• State
  _update:  cleaned up handling of modulation aggregation

* -

* Based on refactor/controlsignals/cost_function

• Function:
  begun moving modulation params (e.g., additive_param and multiplicative_param)
  to Parameter.aliases

* -

* PASSES ALL TESTS EXCEPT LLVM

* -

* -

* • Project
  - final purge of all free-standing multiplicative_param and additive_param attributes in Function classes;
  now they are handled entirely by aliases.
  - still need to purge from and update docstrings

* -

* -

* -

* PRIOR COMMMIT:
• Component
   - __init__:  now checks for function returned in _instantiate_attributes_before_function
                to allow subclass to modify/replace function arg provided in constructor

* -

* • Composition
  - add_projection:  add better error message for projection to node not in graph
  - show_graph: fix bug in which ControlMechanism was sneaking in as an OUTPUT node

* • Composition
  - add_projection:  add better error message for projection to node not in graph
  - show_graph: fix bug in which ControlMechanism was sneaking in as an OUTPUT node

* -

* • Composition:
  - fixed bug in determine_node_roles

* -

* • Merged with most recent devel

* • ModulatorySignal:  docstring mods

* • TransferWithCosts
  - _instantiate_cost_function:  fixed bug in initialization of cost

* -

* -

* -

* • TransferWithCosts:  added _is_identity()

* -

* • ModulatorySignal - revamped docstring

* • ModulatorySignal - revamped docstring

* -

* -

* -

* -

* -

* -

* -

* -

* • TransferWithCosts
  - fixed bugs in assignment of intensity parameter and adjustment_cost

* -

* • TransferWithCosts
  - Parameters:  assigned default to costs with same shape as intensity
  - cobmine_costs_fct: replaced Reduce with LinearCombination

* • tests/functions/test_transfer
  added test_transfer_with_costs

* • TransferWithCosts
  - function: only execute combine_costs_fct if enabled_cost_functions is not None

* • TransferWithCosts
  - set values of costs not computed to None

* • TransferWithCosts: docstring mods

* • Composition
  - "shadow_inputs" > SHADOW_INPUTS
  - added some comments in add_controller

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* • Merged with devel - 9/17/19

* -

* -

* -

* -

* • ControlMechanism - docstring mods

* • Revert, but with updated docstring mods to ControlMechanism

* • Revert, but with updated docstring mods to ControlMechanism

* • ModulatoryMechanism - docstring mods

* llvm, state: Modulation keywords are no longer part of ModulationParam

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

* llvm, component: Don not include ComponenetsMeta type parameters

These are leftovers from local imports and not used at runtime.
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

* llvm, functions/TransferWithCosts: Implement compiled transfer

Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

* • Now passes all tests, although TranserWithCosts is not tested with LLVM

• GatingMechanism - docstring mods (to be consistent with ModulatoryMechanism

* • GatingMechanism - docstring mods (to be consistent with ModulatoryMechanism